name: prosummary
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  record: ^5.0.4
  permission_handler: ^10.0.0 # Replace with the actual version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
